---
#
#  Copyright 2020-2021 Hewlett Packard Enterprise Development LP
# 
#      ALL RIGHTS RESERVED
# 
# Refer full yaml or manual for documentation of the parameters
# Update following parameter values as appropriate to your setup
  
action: sc_status
node: default
pathmon_name: /no/default
sc_name: /no/default
sc_stop_mode: default
config_data:
  pdmi:
    serverclass:
      program: 
        node: default
        file: /usr/tandem/nssjava/jdk180_l80/bin/java
      process_type: OSS
      oss:        
        arglist: [-Dserver.socket.port=5000, com.hpe.nsk.nsdevops.server.Server]
        cwd: /home/dev/app
        env:
          CLASSPATH: ".:bankapp-1.0.jar"             
      max_links:   8
      link_depth:  2
      max_servers: 2
      num_static:  1   
