---
#
#  Copyright 2020-2021 Hewlett Packard Enterprise Development LP
# 
#      ALL RIGHTS RESERVED
# 

# Refer full yaml or manual for documentation of the parameters  
# Update following parameter values as appropriate to your setup

action: pathmon_status
node: default
pathmon_name: /no/default
config_data:
  pdmi:
    pathmon:
      process:
        primary_cpu: 0
        backup_cpu: -1
      control_file:
        node: default
        name: $SYSTEM.DATA01.QA1
      log:
        configuration1:
          node: default
          file: $0 
          format: event
          log_status_messages: yes
