---
#
#  Copyright 2020-2021 Hewlett Packard Enterprise Development LP
# 
#      ALL RIGHTS RESERVED
# 

# Refer full yaml or manual for documentation of the parameters
# Update following parameter values as appropriate to your setup

action: pathway_status
config_data:
  pdmi:
    pathway:
      default_user_mask: default
      max_serverclasses: 200
      max_serverprocesses: 1000
      glink_algorithm: DEFAULT
      long_process_name: default
      rebalance_mode: default
      max_defines: 1000
      max_assigns: 1000
      max_params: 200
      max_startups: 200
      max_linkmons: 16
      node_independent: default
      security: default
      owner:
        node: default
        id: default
