/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hpe_nsk_nsdevops_server_JavaHelloServer */

#ifndef _Included_com_hpe_nsk_nsdevops_server_JavaHelloServer
#define _Included_com_hpe_nsk_nsdevops_server_JavaHelloServer
#ifdef __cplusplus
extern "C" {
#endif
#undef com_hpe_nsk_nsdevops_server_JavaHelloServer_MIN_PRIORITY
#define com_hpe_nsk_nsdevops_server_JavaHelloServer_MIN_PRIORITY 1L
#undef com_hpe_nsk_nsdevops_server_JavaHelloServer_NORM_PRIORITY
#define com_hpe_nsk_nsdevops_server_JavaHelloServer_NORM_PRIORITY 5L
#undef com_hpe_nsk_nsdevops_server_JavaHelloServer_MAX_PRIORITY
#define com_hpe_nsk_nsdevops_server_JavaHelloServer_MAX_PRIORITY 10L
/*
 * Class:     com_hpe_nsk_nsdevops_server_JavaHelloServer
 * Method:    sayHelloNative
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_hpe_nsk_nsdevops_server_JavaHelloServer_sayHelloNative
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
